package vn.hcmut.ap.pim.response;

public enum ResponseCode {
    SUCCESS, PARSER_EXCEPTION, PROJECT_NUMBER_ALREADY_EXIST, VISA_DOSE_NOT_EXIST, INTERNAL_SERVER_ERROR, INVALID_PROJECT_NUMBER, DELETE_PROJECT_ERROR, CONCURRENT_UPDATE_ERROR, NOT_ENOUGH_FIELD, PROJECT_NOT_FOUND
}
